version: '3.1'
services:
  codeBLUE-redis:
    image: redis
    command: redis-server --port 6379
    container_name: codeBLUE-redis
    hostname: redis
    ports:
      - 6379:6379
    restart: unless-stopped
  api-server:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: api-server
    ports:
      - '3000:3000'
    depends_on:
      - codeBLUE-redis