version: '3.1'
services:  
  redis-server:
    image: redis
    command: redis-server --port 6379
    container_name: redis-server
    hostname: redis
    ports:
      - 6379:6379
    restart: unless-stopped
  
  codeblue:
    build:
      context: ./
    container_name: codeblue
    ports:
      - '3000:3000'
    volumes:
      - ./src:/src
      - ./node_modules
    restart: unless-stopped
    depends_on:
      - redis-server